config/routes.rb
require 'sidekiq/web'

Learnror::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :admin do
    resources :products
    resources :categories
    resources :users, only: [:index, :show] do
      resources :permissions, only: [:index, :create, :destroy]
    end
  end
  resources :lots, only: [:index, :show] do
    resources :bets, only: [:create]
  end

  resource :profile

  root to: 'site#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      user.admin? ? admin_abilities : user_abilities(user)
    else
      guest_abilities
    end
  end

  private

  def user_abilities(user)
    can :read, Lot
    can :create, Bet
    can :manage, :profile

    user.permissions.each do |p|
      begin
        can p.action.to_sym, p.subject.constantize, id: p.subject_id
      rescue NameError
        can p.action.to_sym, p.subject.to_sym
      end
    end
  end

  def guest_abilities
    can :read, Lot
  end

  def admin_abilities
    can :manage, :all
  end
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :lot
  belongs_to :user

  validates :lot, :user, presence: true
  #validate :lot_active?

  after_create :update_lot

  private

  def update_lot
    lot.increase_price
    lot.increase_end_time
  end

  def lot_active?
    errors.add(:lot, 'Lot is not active') unless lot.active?
  end
end

app/models/bot.rb
class Bot
  include Sidekiq::Worker
  include Sidetiq::Schedulable

  recurrence { secondly(1) }

  def self.make_bet(lot)
    last_bet = lot.bets.last
    Bet.create(lot: lot, user: User.random_bot) if !last_bet.present? || !last_bet.user.bot?
  end

  def perform
    Lot.ended_soon.each { |lot| Bot.delay.make_bet(lot) }
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  has_many :bets

  scope :ended_soon, -> { where("(end_time - now()) <= interval '5 sec' AND (end_time - now()) > interval '1 sec'") }

  def increase_price
    self.price += 1
    self.save!
  end

  def increase_end_time
  end

  def active?
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  validates :title, :action, :subject, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images

  validates :title, presence: true

  accepts_nested_attributes_for :images
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations, dependent: :destroy

  has_many :user_permissions
  has_many :permissions, through: :user_permissions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :vkontakte]

  scope :bots, -> { where(bot: true) }

  #validates :first_name, :last_name, presence: true

  def self.random_bot
    bots.order('RANDOM()').first
  end

  def self.find_for_oauth(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    if authorization
      user = authorization.user
    else
      email = auth.info[:email]
      user = User.where(email: email).first
      if user
        user.create_authorization(auth)
      else
        if email.present?
          password = Devise.friendly_token[0, 20]
          user = User.create(email: email, password: password, password_confirmation: password)
          user.create_authorization(auth)
        end
      end
    end
    user
  end

  def create_authorization(auth)
    self.authorizations.create!(provider: auth.provider, uid: auth.uid)
  end

  def add_authorization(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    if authorization
      authorization.user == self
    else
      create_authorization(auth)
      true
    end
  end

  def self.calculate_raiting
    self.all.each { |u| u.delay.calculate_raiting }
  end

  def calculate_raiting
    puts 'Sart'
    sleep(40)
    #Notifier.delay.signup
    puts 'End'
  end
end

app/models/user_permission.rb
class UserPermission < ActiveRecord::Base
  belongs_to :user
  belongs_to :permission
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do
    render file: "#{Rails.root}/public/403.html", status: 403
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end
end

app/controllers/bets_controller.rb
class BetsController < InheritedResources::Base
  belongs_to :lot

  respond_to :js
  actions :create

  def create
    create! do |success, failure|
      success.js do
        PrivatePub.publish_to '/lots/update', lot_id: resource.lot.id, end_time: resource.lot.end_time.to_s
        render nothing: true
      end
    end
  end
end

app/controllers/lots_controller.rb
class LotsController < InheritedResources::Base
  respond_to :html
  actions :index, :show

  before_action :authenticate_user!
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :oauth_callback

  def facebook
  end

  def vkontakte
  end

  protected

  def oauth_callback
    auth = request.env['omniauth.auth']

    if signed_in?
      if current_user.add_authorization(auth)
        flash[:notice] = 'Соц. сеть успешно добавлена'
      else
        flash[:error] = 'Соц. сеть уже связана с другим аккаунтом'
      end
      redirect_to profile_path
    else
      @user = User.find_for_oauth(auth)

      if @user && @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        flash[:notice] = 'Вы успешно вошли через соц. сеть' if is_navigational_format?
      else
        flash[:notice] = "Пожалуйста, завершите регистрацию."
        session['devise.oauth'] = auth
        redirect_to new_user_registration_path
      end
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  before_action :authorize_resource

  def show
  end

  private

  def authorize_resource
    authorize! :manage, :profile
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    @user = User.new
    auth = session['devise.oauth']

    if auth.present?
      @user.first_name = auth[:info][:first_name]
      @user.last_name = auth[:info][:last_name]
    end
  end

  def create
    super do |resource|
      resource.create_authorization(session['devise.oauth'])
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Learnror"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "admin/admin", :media => "all"
    = javascript_include_tag "admin/admin"



  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Learnror
          .container.nav-collapse
            ul.nav
              li= link_to "Products", admin_products_path
              li= link_to "Categories", admin_categories_path
              li= link_to "Users", admin_users_path
              li= link_to "Log out", destroy_user_session_path, method: :delete
    .container
      .main
        .row
          .span9
            = bootstrap_flash
            = yield
          .span3
            .well.sidebar-nav
              h3 Sidebar
              ul.nav.nav-list
                li.nav-header Sidebar
                li= link_to "Link 1", "/path1"
                li= link_to "Link 2", "/path2"
                li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2013

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Learnror"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"



  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#"Learnror
          .container.nav-collapse
            ul.nav
              li= link_to "Products", admin_products_path
              li= link_to "Lots", lots_path
              - if user_signed_in?
                li= link_to 'Profile', profile_path
                li= link_to "Log out", destroy_user_session_path, method: :delete

    .container
      .main
        .row
          .span9
            = bootstrap_flash
            = yield
          .span3
            .well.sidebar-nav
              h3 Sidebar
              ul.nav.nav-list
                li.nav-header Sidebar
                li= link_to "Link 1", "/path1"
                li= link_to "Link 2", "/path2"
                li= link_to "Link 3", "/path3"
    
      footer
        p &copy; Company 2013

app/views/notifier/signup.text.slim
Notifier#signup

= @greeting + ", find me in app/views/notifier/signup.text.slim"